### PR TITLE
feature: bitmex eth perpetual contract support

### PR DESCRIPTION
**Pull request by dmitry-ee**
BITMEX opened ETH contracts since 02 aug
https://www.bitmex.com/app/contract/ETHUSD
So, why not?

### CODE REVIEW

**Comment by Tucsky** [comment]
Thanks you man :+1: 

Upcoming version retrieve exchanges products automatically tho, much more reliable on the long term
https://ethusd.aggr.trade/

Still **a lot** of bugs but I'm getting there :-)
https://github.com/Tucsky/SignificantTrades/tree/feature/standalone

**Comment by dmitry-ee** [comment]
NP mate.
I'm going to make docker image for your server (for fast deploy and scaling).
Are you not interested to split server and web parts?

**Comment by Tucsky** [comment]
Absolutely, and since I can't open tens of thousands WS channel at once to track all possible pairs that exists I would like to **get rid of that server part completly** in the future. Thats the main reason why **feature/standalone** exists.

The current server part has been moved to **feature/server** 
It currently serve three purposes
- the old BTCUSD ws trade feed @ http://tucsky.github.io/SignificantTrades
- the BTCUSD trade history rest API
- as a cors proxy for https://aggr.trade (since it fetch symbols using AJAX and half the exchanges doesn't allow direct ajax access to their rest api)

Today the server is located at api.aggr.trade but tomorrow I will probably split the CORS proxy & Trade API in two different nodes
- cors.aggr.trade (even tho I wish I could find a better solution to send direct req to exchanges from aggr.trade client)
- api.aggr.trade
so aggr.trade will still work fine if the github pages url is overloaded

Its a little messy right now but changes need to be done since the server crashed yesterday du to heavy traffic (first time it happened), so yeah... no experience in Docker myself but it does need scaling :smile: 
Obviously the historical trade api is the part that caused the crash, as its just hundred of thousands of trades in fucking .txt files, so yeah not the best scalable thing in the world I guess, I wish I could move to a very light nosql solution soon.

**Comment by dmitry-ee** [comment]
Hi, mate!
Look what i've got:
https://github.com/dmitry-ee/SignificantTrades/tree/feature/server#run-container-standalone-without-docker-compose

I've found Docker as much simplier way to scale and maintain apps.
Deploy just in 50 seconds (if you don't have an image) and less than 1 second (if image is cached)

Are you interested in merge?

_I'm using your project as dependency for https://github.com/dmitry-ee/significant-trades-elk-exporter
That's a listener for your app and exporter to elasticsearch_

**Comment by Tucsky** [comment]
Hi

Nice work man,
I tried it and docker gives me an error when I type *$ make build*
WARNING: The DEFAULT_PORT variable is not set. Defaulting to a blank
string.ERROR: The Compose file './docker-compose.yml' is invalid
because:services.significant-trades-server.ports contains an invalid type,
it should be a number, or an object
make: *** [build] Error 1
I un commented the variables in .env same result, I'm using osx btw.

> Are you interested in merge?
>
Absolutely,
docker is a good way to setup a project quicky using generic procedure,
many people use it, I don't maybe thats why I'm getting this :)


> *I'm using your project as dependency
> for https://github.com/dmitry-ee/significant-trades-elk-exporter
> <https://github.com/dmitry-ee/significant-trades-elk-exporter>That's a
> listener for your app and exporter to elasticsearch*
>
Wow that's amazing! I was thinking of finally move to another storing
solution for the trades
(.txt is pretty stupid lol), and offer more flexibility in order to query
them,
like a very light nosql db or smth.
How do you think ES would perform when querying trades between 2 timestamp
and a specific exchange ?


Kevin Rostagni
kevinrostagni.codes | +33 6 66 44 56 88

**Comment by dmitry-ee** [comment]
Hi!
Thanks!

> I tried it and docker gives me an error when I type *$ make build*
WARNING: The DEFAULT_PORT variable is not set. Defaulting to a blank

I fixed that issue, it caused by my shell pre-exported variables.
Try it now, i tested on OSX tho.

> like a very light nosql db or smth.
I really like MongoDB for that purpose, but you need to build your own api to retrieve and aggregate data.

> How do you think ES would perform when querying trades between 2 timestamp and a specific exchange ?

I works really great, you can check it with my another project: https://github.com/dmitry-ee/significant-trades-cluster
Runs just with one `make`
(Notice: if you are on OSX you need to share /data directory in Docker preferences)
Project contains from: 4 nodes of exporter, 4 nodes of your server, elasticsearch + kibana
It aggregates 4 currency pairs: BTC/USD, ETH/USD, BCH/USD, XRP/USD (but really you can do much more).
After launch you need to wait a little bit, cause elastic lanuch is not so fast (you can check it via `docker ps`)
Even on my 7 year old notebook (with desktop ubuntu) with 8GB memory it performs really great without any lag, and there is still free memory :rofl: 

I want to complete cluster project and make it much more flexible with ansible templating.
My purpose is to make cluster that consumes small config like: 
pairs: BCH/USD, RLC/BTC, ...
And it should deploy all necessary stuff (even with dashboards and etc. inside kibana)

**Pull request merged**
